[tool.poetry]
name = "my-project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.13"
Flask = "*"
pandas = "*"
scikit-learn = "*"
joblib = "*"
requests = "*"
gunicorn = "*"
geopy = "*"